### ISSUE TITLE
Portfolio Themes

### ISSUE THREAD

**Issue by cogdog** [TWUOnline/planning#1]
The HTML5up themes are good but there is not enough time to make them Wordpress solid, not to mention the question of Gutenburg (a big black hole to me now). 

I recommend staying with exisiing Wordpress themes, and mores o, since using JetPack, you get access to built-in support for both [portfolio custom post types and testimonial ones](https://jetpack.com/support/custom-content-types/)-- see the info for [Portfolio Custom Post types](https://en.support.wordpress.com/portfolios/) especially the listed themes which are designed to work with them- these themes seem to have more than enough for what you need. The portfolio content has its own taxonomy, so students could use regular posts for writing their own updates, reflections.

**Comment by cmadland** [comment]
That makes good sense, especially on such a short timeline. I'll have a look at that documentation and the recommended themes. I've got several Anders Noren themes already on the site and I know you've used those in the past. Would one of those work?

**Comment by cmadland** [comment]
Ok, I've had a look at the portfolio custom post type page and the links to themes there.

I really like Blask, Argent, and Illustratr as linked there.

[Radcliffe 2](https://wordpress.com/theme/radcliffe-2) looks good too.

Feel free to fork the repo to propose changes...

**Comment by cogdog** [comment]
The Anders Noren themes may work okay; the thing about these other things is they already have templates set for portfolio type content. Radcliffe might be a good choice for a more text-based one.

**Comment by cogdog** [comment]
Starting with:

Illustrator https://wordpress.org/themes/illustratr
Argent https://wordpress.org/themes/argent/
Radcliffe2 - manually downloaded and installed
