### ISSUE TITLE
Portfolio Meta Data

### ISSUE THREAD

**Issue by cogdog** [TWUOnline/planning#2]
Beyond the listed Student Learning Outcome taxonomy (this can fit as something preset into the portfolio taxonomy, or can be added as a custom one), I'd like some better idea what elements might be needed for  portfolio items, what other kinds of info do you want in a portfolio item? Do they link it to a particular class, department? Is there media type? etc

**Comment by cmadland** [comment]
I will do that...but not tonight as I have a presentation tomorrow that needs a bunch of work.
