### ISSUE TITLE
Memory Limit

### ISSUE THREAD

**Issue by cogdog** [TWUOnline/planning#5]
Worth a call to Reclaim

![host-limit](https://user-images.githubusercontent.com/463038/43145207-164fb89c-8f1c-11e8-85c6-37bfb9feeef1.jpg)

**Comment by cmadland** [comment]
Yeah, we were running into PHP memory limit errors before we upped to a dedicated server. Tim had increased the limit to 1 GB or something, then we still ran into errors on the new server. Tim’s solution was to set it to -1mb, which apparently is equal to ‘no limit’.

He was a little stumped as to why it was behaving like that. We variously blamed it on WordFence and DobsonDev Shortcodes, depending which one would fix the problem when turned off.

It never seemed to affect users on individual sites, only superadmins.

cm


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
604.513.2121 ext. 3876 |  colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

Trinity Western University is located on traditional ancestral unceded territory of the Sto:lo people.

On Jul 24, 2018, at 7:32 AM, Alan Levine <notifications@github.com<mailto:notifications@github.com>> wrote:


Worth a call to Reclaim

[host-limit]<https://user-images.githubusercontent.com/463038/43145207-164fb89c-8f1c-11e8-85c6-37bfb9feeef1.jpg>
